repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^venv/
      - id: end-of-file-fixer
        exclude: ^venv/
      - id: check-yaml
        exclude: ^venv/
      - id: check-added-large-files
        exclude: ^venv/
      - id: check-merge-conflict
        exclude: ^venv/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^venv/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^venv/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^venv/
